### ISSUE TITLE
504 gateway timeout

### ISSUE THREAD

**Issue by Blank-Git-hub** [hos1818/bandwidth-hero-vercel#1]
I am using it in ~tachiyomi~ aniyome, sometime images load but sometime they dont. When i check my log in vercel it shown error like 504 gateway timeout and Invalid parameters: originType or originSize missing/invalid. it works compleatly fine with your link. What to do.

**Comment by hos1818** [comment]
increase Function Max Duration to 60
![image](https://github.com/user-attachments/assets/2d6fe1dd-2315-4020-8135-3912cfc02e5f)

**Comment by hos1818** [comment]
this problem occurs because the the conversion to avif takes more time than the default value of Function Max Duration

**Comment by hos1818** [comment]
for a hobby plan, you can set it up to 60.
yes I added it in the readme after I sent it to you
