### ISSUE TITLE
Compression optimization

### ISSUE THREAD

**Issue by Blank-Git-hub** [hos1818/bandwidth-hero-vercel#3]
This is continuation of the issue i posted first https://github.com/hos1818/bandwidth-hero-vercel/issues/1#issuecomment-2411571003
>Somthing else i notice when comparing orignal vs low quality, that lower quality one actally more in size, it seems to be compressing larger images harder.

There is an issue with how compression scale. here asuracomic is high quality source😄 and manhuafast low quality😠.

Asuracomic orignal https://gg.asuracomic.net/storage/media/244469/conversions/01-optimized.webp *-508.98kb*
Asuracomic compressed
https://bandwidth-hero-cfg-wy12.vercel.app/?jpg=1&l=80&bw=0&url=https%3A%2F%2Fgg.asuracomic.net%2Fstorage%2Fmedia%2F244469%2Fconversions%2F01-optimized.webp *-227.57kb*
Which is *55.289%* decrease
Manhuafast orignal
https://cdn.manhuafast.com/image2024/manga_63ac5507b1a1b/949cb2f56c314ff5d4c4691bd7fdc6d0/001.webp *-413.82kb*
Manhuafast compressed
https://bandwidth-hero-cfg-wy12.vercel.app/?jpg=1&l=80&bw=0&url=https%3A%2F%2Fcdn.manhuafast.com%2Fimage2024%2Fmanga_63ac5507b1a1b%2F949cb2f56c314ff5d4c4691bd7fdc6d0%2F001.webp *-353.03kb*
Which is *14.69%* decrease 

Asuracomics<manhuafast by *−125.46kb* or *-35.5381%* in both of there compessed state. Which i don't think should be. 
https://github.com/hos1818/bandwidth-hero-vercel/issues/1#issuecomment-2411571003 
>Here is my observation. When i read manhwa from lower quality source rather then orignal scans it works.
When i am reading same manhwa from same low quality source but pages are split in larger chunks half to be exact it wont work.

In those 2 in 1 page visual quality is much more noticeably lower, though i didn't check there size and i don't remember what chapter were they. If you really want an example i could try digging through them (peronally it doesn't have much affect on me, less data the better).

**Comment by hos1818** [comment]
first comment, the size of the compressed image depends on the source image size.
Second comment, I did some optimization, so check it now
